### ISSUE TITLE
Add "validation_status" and "validation_timestamp" if ckan/ckanext-scheming#168 goes forward

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/ckanext-validation#16]
Comment by @amercader removed from our README file on https://github.com/frictionlessdata/ckanext-validation/blob/4321b7973d5b99fdd2f5dfa9791ddb775ef3a83f/README.md#changes-in-the-schema

Related to https://github.com/ckan/ckanext-scheming/pull/168

**Comment by amercader** [comment]
I ended up implementing in a different way, so the comment is no longer relevant. These two fields are now listed in the example schema: https://github.com/frictionlessdata/ckanext-validation#changes-in-the-schema
