### ISSUE TITLE
Don't show Edit button when you click on other options

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-validation#32]
If you click on Upload , Link or JSON the "Edit" button should disappear to be consistent.

A related but separate issue is whether you should be able to edit existing schemas (uploaded or pasted in the JSON field) with the editor. I think you should. In practice that would mean prefilling the editor component with the contents of the hidden `schema` field, if present and with a value.

**Comment by roll** [comment]
So we support provided schema editing (e.g. upload schema and click edit) - so the thing here to decide what's the best UI for on the form level.

**Comment by roll** [comment]
FIxed/Moved in #25/#34
