### ISSUE TITLE
Make Schema Editor responsive

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-validation#36]
![screen shot 2018-04-17 at 12 30 24](https://user-images.githubusercontent.com/200230/38864498-34df1d08-423b-11e8-8b6d-9f2d418063bf.png)
![screenshot-2018-4-17 add resource - test dataset proper org - ckan](https://user-images.githubusercontent.com/200230/38864499-34fc53f0-423b-11e8-89c7-d5780f536b70.png)

**Comment by roll** [comment]
The editor itself on bs3 should be responsive. I guess it's a integration/ bs2 backport issue
