### ISSUE TITLE
Improve layout of schema creator

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-validation#37]
![screenshot-2018-4-17 add resource - test dataset proper org - ckan 1](https://user-images.githubusercontent.com/200230/38864551-5e3352dc-423b-11e8-9b59-c88b58e72412.png)

@roll not sure how easy it is to do that of it is part of the component layout but it would be great if we could get rid of the "Edit" button on top and move the "Save" one to the bottom right, ideally with the same styling that the other CKAN buttons. Also the "Add Field" smaller, in the lower right corner as well or somewhere else.

We can wait until @smth has a proper look at the whole UI, but I just want to know if it's easy to modify the layout from this extension.

**Comment by roll** [comment]
I think it should be easily doable in pure CSS on CKAN side.
